//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeusAutomationSuite
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Objects
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Objects()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZeusAutomationSuite.Objects", typeof(Objects).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to name:8.
        /// </summary>
        public static string Android_Calc_EightButton
        {
            get
            {
                return ResourceManager.GetString("Android_Calc_EightButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to name:=.
        /// </summary>
        public static string Android_Calc_EqualsButton
        {
            get
            {
                return ResourceManager.GetString("Android_Calc_EqualsButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to name:+.
        /// </summary>
        public static string Android_Calc_PlusButton
        {
            get
            {
                return ResourceManager.GetString("Android_Calc_PlusButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to class:android.widget.EditText.
        /// </summary>
        public static string Android_Calc_ResultPane
        {
            get
            {
                return ResourceManager.GetString("Android_Calc_ResultPane", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to name:7.
        /// </summary>
        public static string Android_Calc_SevenButton
        {
            get
            {
                return ResourceManager.GetString("Android_Calc_SevenButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to rcTB.
        /// </summary>
        public static string Bing_SearchResultBox
        {
            get
            {
                return ResourceManager.GetString("Bing_SearchResultBox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to name:q.
        /// </summary>
        public static string BingHome_SearchBox
        {
            get
            {
                return ResourceManager.GetString("BingHome_SearchBox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to sb_form_go.
        /// </summary>
        public static string BingHome_SearchButton
        {
            get
            {
                return ResourceManager.GetString("BingHome_SearchButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to name:Blank workbook.
        /// </summary>
        public static string Excel_BlankSheet_Option
        {
            get
            {
                return ResourceManager.GetString("Excel_BlankSheet_Option", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to name:A1.
        /// </summary>
        public static string Excel_CellA1
        {
            get
            {
                return ResourceManager.GetString("Excel_CellA1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to name:Formula Bar.
        /// </summary>
        public static string Excel_Formulabar
        {
            get
            {
                return ResourceManager.GetString("Excel_Formulabar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to sb_form_go.
        /// </summary>
        public static string Google_SearchPage_SearchButton
        {
            get
            {
                return ResourceManager.GetString("Google_SearchPage_SearchButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to sb_form_q.
        /// </summary>
        public static string Google_SearchPage_TextBox
        {
            get
            {
                return ResourceManager.GetString("Google_SearchPage_TextBox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to class:login-btn.
        /// </summary>
        public static string LoginPage_LoginButton
        {
            get
            {
                return ResourceManager.GetString("LoginPage_LoginButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SingPassId.
        /// </summary>
        public static string LoginPage_SingPassID
        {
            get
            {
                return ResourceManager.GetString("LoginPage_SingPassID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to innertext:Tools.
        /// </summary>
        public static string PortalServicePage_ToolsLink
        {
            get
            {
                return ResourceManager.GetString("PortalServicePage_ToolsLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to xpath://*[@id=&quot;_TwentyYearsInput&quot;]/div[1]/div[1]/span/span.
        /// </summary>
        public static string RetirementEst_Claculator_Agevalidation
        {
            get
            {
                return ResourceManager.GetString("RetirementEst_Claculator_Agevalidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BonusNumberOfMonths_display.
        /// </summary>
        public static string RetirementEst_Claculator_Bonus
        {
            get
            {
                return ResourceManager.GetString("RetirementEst_Claculator_Bonus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to calculateButton.
        /// </summary>
        public static string RetirementEst_Claculator_Calculate
        {
            get
            {
                return ResourceManager.GetString("RetirementEst_Claculator_Calculate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CurrentAge_display.
        /// </summary>
        public static string RetirementEst_Claculator_CurrentAge
        {
            get
            {
                return ResourceManager.GetString("RetirementEst_Claculator_CurrentAge", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RetirementNeeds_AverageInflationRate.
        /// </summary>
        public static string RetirementEst_Claculator_inflationrate
        {
            get
            {
                return ResourceManager.GetString("RetirementEst_Claculator_inflationrate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to xpath://*[@id=&quot;_TwentyYearsInput&quot;]/div[1]/div[2]/span/span.
        /// </summary>
        public static string RetirementEst_Claculator_MessageForIncome
        {
            get
            {
                return ResourceManager.GetString("RetirementEst_Claculator_MessageForIncome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CurrentMonthlyIncome_display.
        /// </summary>
        public static string RetirementEst_Claculator_MonthlyIncome
        {
            get
            {
                return ResourceManager.GetString("RetirementEst_Claculator_MonthlyIncome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to cpfPageTitle.
        /// </summary>
        public static string RetirementEst_Claculator_PageName
        {
            get
            {
                return ResourceManager.GetString("RetirementEst_Claculator_PageName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RetirementNeeds_ReturnOnInvestmentDuringRetirement.
        /// </summary>
        public static string RetirementEst_Claculator_ROI
        {
            get
            {
                return ResourceManager.GetString("RetirementEst_Claculator_ROI", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to is-disclaimer-checked.
        /// </summary>
        public static string RetirementEst_DisclaimerCheckBox
        {
            get
            {
                return ResourceManager.GetString("RetirementEst_DisclaimerCheckBox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IsFixedPeriodSelectedFalse.
        /// </summary>
        public static string RetirementEst_Option1
        {
            get
            {
                return ResourceManager.GetString("RetirementEst_Option1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to class:cpf-btn-p.
        /// </summary>
        public static string RetirementEst_Start
        {
            get
            {
                return ResourceManager.GetString("RetirementEst_Start", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to innertext:CPF Retirement Estimator.
        /// </summary>
        public static string ToolsPage_RetirementEstimator
        {
            get
            {
                return ResourceManager.GetString("ToolsPage_RetirementEstimator", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to name:Eight.
        /// </summary>
        public static string UWP_Calc_EightButton
        {
            get
            {
                return ResourceManager.GetString("UWP_Calc_EightButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to name:Equals.
        /// </summary>
        public static string UWP_Calc_EqualsButton
        {
            get
            {
                return ResourceManager.GetString("UWP_Calc_EqualsButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to name:Plus.
        /// </summary>
        public static string UWP_Calc_PlusButton
        {
            get
            {
                return ResourceManager.GetString("UWP_Calc_PlusButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to aceesibilityid:CalculatorResults.
        /// </summary>
        public static string UWP_Calc_ResultPane
        {
            get
            {
                return ResourceManager.GetString("UWP_Calc_ResultPane", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to name:Seven.
        /// </summary>
        public static string UWP_Calc_SevenButton
        {
            get
            {
                return ResourceManager.GetString("UWP_Calc_SevenButton", resourceCulture);
            }
        }
    }
}
